default: &default
  ligo_salt_for_id_concealer: "salted_id_for_ligo_core"
  ligo_password_reset_token_expiry_minutes: 5
  ligo_email_verification_token_expiry_minutes: 60
  ligo_app_cors_whitelist: "*"
  ligo_app_cors_ok_headers: "Content-Type, Authorization, Access-Control-Allow-Origin"

  ligo_redis_host: "127.0.0.1"
  ligo_redis_port: 6379
  ligo_redis_password: ""
  ligo_redis_database_number: 0

  ligo_sidekiq_redis_host: "127.0.0.1"
  ligo_sidekiq_redis_port: 6379
  ligo_sidekiq_redis_password: ""
  ligo_sidekiq_redis_database_number: 0
  ligo_sidekiq_dashboard_session_secret: ""
  ligo_sidekiq_job_status_expiry: 86400

  ligo_mailer_from_email: "noreply@example.com"
  ligo_mailer_from_name: "Ligo"
  ligo_mailer_app_name: "Ligo"
  ligo_mailer_app_description: "Ligo is the shared engine behind our apps."

development: &development
  <<: *default

  ligo_mailer_smtp_host: "localhost"
  ligo_mailer_smtp_port: 1026
  ligo_mailer_smtp_use_auth: false

test:
  <<: *development

production:
  <<: *default
