default: &default
  ligo_salt_for_id_concealer: "salted_id_for_ligo_core"
  ligo_password_reset_token_expiry_minutes: 5
  ligo_email_verification_token_expiry_minutes: 60
  ligo_app_cors_whitelist: "*"
  ligo_app_cors_ok_headers: "Content-Type, Authorization, Access-Control-Allow-Origin"

  ligo_redis_host: "127.0.0.1"
  ligo_redis_port: 6379
  ligo_redis_password: ""
  ligo_redis_database_number: 0

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
