# Generated by Marten 0.7.0 on 2026-09-13 22:34:25 +09:00

class Migration::Ligo::V202609132234251 < Marten::Migration
  depends_on :ligo, "202609132217201_add_iam_identifier_to_user"

  def plan
    create_table :ligo_webhook_delivery do
      column :deleted_at, :date_time, null: true, index: true
      column :id, :big_int, primary_key: true, auto: true
      column :content_id, :string, max_size: 200
      column :succeeded, :bool
      column :created_at, :date_time
      column :updated_at, :date_time
    end

    create_table :ligo_realm do
      column :deleted_at, :date_time, null: true, index: true
      column :id, :string, max_size: 12, primary_key: true
      column :app_name, :string, max_size: 255
      column :hashed_api_secret_key, :string, max_size: 65
      column :hashed_api_client_key, :string, max_size: 65
      column :webhook_secret, :string, max_size: 15
      column :ack_semantic, :enum, values: ["NONE", "OPTIONAL", "MUTUAL"]
      column :max_ack_retry_attempts, :int, null: true, default: 50
      column :registration_redirection_uri, :string, max_size: 200, null: true
      column :registration_ack_uri, :string, max_size: 200, null: true
      column :app_id, :string, max_size: 255
      column :app_secret, :string, max_size: 255
      column :default_role, :int, default: 9000
      column :created_at, :date_time
      column :updated_at, :date_time
    end

    create_table :ligo_realm_user do
      column :id, :big_int, primary_key: true, auto: true
      column :provider, :int, index: true
      column :provider_user_id, :string, max_size: 255, index: true
      column :acked_at, :date_time, null: true
      column :registration_webhook_content_id, :string, max_size: 255, null: true
      column :created_at, :date_time
      column :updated_at, :date_time
      column :user_id, :reference, to_table: :ligo_user, to_column: :id
      column :realm_id, :reference, to_table: :ligo_realm, to_column: :id
    end

    add_unique_constraint :ligo_realm_user, :idx_provider_provider_user_id_unique, [:provider, :provider_user_id, :realm_id]
  end
end
