# Generated by Marten 0.7.0 on 2026-09-13 22:17:20 +09:00

class Migration::Ligo::V202609132217201 < Marten::Migration
  depends_on :ligo, "202609132115111_create_ligo_changelog_table"

  def plan
    add_column :ligo_user, :iam_identifier_primary, :string, max_size: 255, null: true, index: true
  end
end
