# Generated by Marten 0.7.0 on 2026-09-13 21:15:11 +09:00

class Migration::Ligo::V202609132115111 < Marten::Migration
  depends_on :ligo, "202609132027081_create_field_def_value"

  def plan
    create_table :ligo_changelog do
      column :id, :big_int, primary_key: true, auto: true
      column :action_type, :enum, values: ["CREATE", "UPDATE", "DELETE"]
      column :record_class, :string, max_size: 255
      column :record_id, :big_int, null: true
      column :record_uuid, :uuid, null: true
      column :changes, :json, null: true
      column :performer_id, :big_int, null: true
      column :created_at, :date_time
      column :updated_at, :date_time
    end
  end
end
