# Generated by Marten 0.7.0 on 2026-09-13 19:43:01 +09:00

class Migration::Ligo::V202609131943011 < Marten::Migration
  def plan
    create_table :ligo_organization do
      column :deleted_at, :date_time, null: true, index: true
      column :id, :big_int, primary_key: true, auto: true
      column :name, :string, max_size: 255
      column :created_at, :date_time
      column :updated_at, :date_time
    end

    create_table :ligo_user do
      column :id, :big_int, primary_key: true, auto: true
      column :email, :string, max_size: 254, unique: true
      column :password, :string, max_size: 128
      column :created_at, :date_time
      column :updated_at, :date_time
      column :deleted_at, :date_time, null: true, index: true
      column :first_name, :string, max_size: 255
      column :last_name, :string, max_size: 255, null: true
      column :locale, :string, max_size: 7, default: "en-US"
      column :timezone_offset_seconds, :int, null: true
      column :role, :int, index: true, default: 1000
      column :password_updated_at, :date_time
      column :reset_password_token, :string, max_size: 255, null: true
      column :reset_password_token_created_at, :date_time, null: true
      column :uploaded_profile_picture_file_id, :uuid, null: true
      column :is_email_address_verified, :bool, default: false
      column :email_verification_token, :string, max_size: 255, null: true
      column :email_verification_token_created_at, :date_time, null: true
      column :email_verification_token_expired_at, :date_time, null: true
      column :organization_id, :reference, to_table: :ligo_organization, to_column: :id, null: true
    end
  end
end
