# Generated by Marten 0.7.0 on 2026-09-13 20:27:08 +09:00

class Migration::Ligo::V202609132027081 < Marten::Migration
  depends_on :ligo, "202609131957591_create_uploaded_file"

  def plan
    create_table :ligo_field_definition do
      column :deleted_at, :date_time, null: true, index: true
      column :id, :big_int, primary_key: true, auto: true
      column :name, :string, max_size: 255
      column :localized_name, :json, null: true
      column :metadata, :json, null: true
      column :resource_type, :int, index: true
      column :data_type, :int
      column :is_system_field, :bool, default: false
      column :nullable, :bool, default: true
      column :uniqueness, :enum, values: ["UNIQUELESS", "UNIQUE_ALWAYS", "UNIQUE_FILL"], default: "UNIQUELESS"
      column :created_at, :date_time
      column :updated_at, :date_time
    end

    create_table :ligo_field_value do
      column :deleted_at, :date_time, null: true, index: true
      column :id, :uuid, primary_key: true
      column :resource_id, :big_int
      column :resource_type, :int
      column :string_value, :string, max_size: 255, null: true
      column :text_value, :text, null: true
      column :integer_value, :big_int, null: true
      column :float_value, :float, null: true
      column :date_value, :date, null: true
      column :time_value, :date_time, null: true
      column :datetime_value, :date_time, null: true
      column :boolean_value, :bool, null: true
      column :created_at, :date_time
      column :updated_at, :date_time
      column :field_def_id, :reference, to_table: :ligo_field_definition, to_column: :id
    end

    add_unique_constraint :ligo_field_value, :idx_field_value_field_def_resource_unique, [:field_def_id, :resource_id, :resource_type]
  end
end
