# Generated by Marten 0.7.0 on 2026-09-13 19:57:59 +09:00

class Migration::Ligo::V202609131957591 < Marten::Migration
  depends_on :ligo, "202609131943011_create_user_organization"

  def plan
    create_table :ligo_uploaded_file do
      column :deleted_at, :date_time, null: true, index: true
      column :id, :uuid, primary_key: true
      column :original_name, :string, max_size: 255
      column :content_type, :string, max_size: 127
      column :byte_size, :big_int
      column :created_at, :date_time
      column :updated_at, :date_time
      column :uploaded_by_id, :reference, to_table: :ligo_user, to_column: :id, null: true
    end
  end
end
